id: I04F024B0
legacy_id: P001822
ocr_import_info:
  bdrc_scan_id: W1KG22609
  source: bdrc
  ocr_info:
    timestamp: '2020-03-30T14:03:33'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T13:16:29.447097+00:00'
last_modified: 2022-08-31 21:18:24.133196
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG22609
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1KG22609
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: དམ་ཆོས་དགོངས་པ་ཡང་ཟབ་ཀྱི་ཆོས་སྐོར་ཕྱོགས་བསྒྲིགས།
  author: རྒྱལ་དབང་རིན་ཆེན་ཕུན་ཚོགས།
statistics:
  ocr_word_mean_confidence_index: 0.9259997177409334
  ocr_word_median_confidence_index: 0.9800000190734863
quality: null
bases:
  I1KG22622:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG22622
      total_pages: 476
      volume_number: 6
      volume_pages_bdrc_intro: 2
    order: 6
    base_file: I1KG22622.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9517646700763521
    legacy_id: v006
  I1KG22623:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG22623
      total_pages: 336
      volume_number: 7
      volume_pages_bdrc_intro: 2
    order: 7
    base_file: I1KG22623.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9190060820250967
    legacy_id: v007
  I1KG22620:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG22620
      total_pages: 594
      volume_number: 4
      volume_pages_bdrc_intro: 2
    order: 4
    base_file: I1KG22620.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9247771902291357
    legacy_id: v004
  I1KG22621:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG22621
      total_pages: 586
      volume_number: 5
      volume_pages_bdrc_intro: 2
    order: 5
    base_file: I1KG22621.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9254277598767913
    legacy_id: v005
  I1KG22618:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG22618
      total_pages: 880
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I1KG22618.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9269238780287213
    legacy_id: v002
  I1KG22619:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG22619
      total_pages: 570
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I1KG22619.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.935163883334763
    legacy_id: v003
  I1KG22624:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG22624
      total_pages: 200
      volume_number: 8
      volume_pages_bdrc_intro: 2
    order: 8
    base_file: I1KG22624.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.8857515379414971
    legacy_id: v008
  I1KG22617:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG22617
      total_pages: 510
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG22617.txt
    statistics:
      ocr_word_median_confidence_index: 0.9599999785423279
      ocr_word_mean_confidence_index: 0.8871424804569464
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
