id: I04F024B0
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-30T14:05:30+00:00'
last_modified: '2022-06-07T15:16:28.438140+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG22609
  title: དམ་ཆོས་དགོངས་པ་ཡང་ཟབ་ཀྱི་ཆོས་སྐོར་ཕྱོགས་བསྒྲིགས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    715E:
      image_group_id: I1KG22617
      title: ''
      total_pages: 510
      order: 1
      base_file: 715E.txt
    38B8:
      image_group_id: I1KG22618
      title: ''
      total_pages: 880
      order: 2
      base_file: 38B8.txt
    E87E:
      image_group_id: I1KG22619
      title: ''
      total_pages: 570
      order: 3
      base_file: E87E.txt
    F349:
      image_group_id: I1KG22620
      title: ''
      total_pages: 594
      order: 4
      base_file: F349.txt
    '5901':
      image_group_id: I1KG22621
      title: ''
      total_pages: 586
      order: 5
      base_file: 5901.txt
    '5492':
      image_group_id: I1KG22622
      title: ''
      total_pages: 476
      order: 6
      base_file: 5492.txt
    AAEE:
      image_group_id: I1KG22623
      title: ''
      total_pages: 336
      order: 7
      base_file: AAEE.txt
    E445:
      image_group_id: I1KG22624
      title: ''
      total_pages: 200
      order: 8
      base_file: E445.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
